### ISSUE TITLE
Team Fortress 2

### ISSUE THREAD

**Issue by BlueHairMinerBoy** [galexrt/srcds_exporter#4]
Trying to run it against a TF2 server - getting the following:
`FATA[0000] rcon: could not parse timeout duration        err="time: invalid duration \"\""`

`status` from console is as follows:

```
] rcon status
hostname: fruit server
version : 6809746/24 6809746 secure
udp/ip  : 10.65.65.61:27015
account : not logged in  (No account specified)
map     : ctf_2fort at: 0 x, 0 y, 0 z
tags    : ctf
players : 0 humans, 0 bots (24 max)
edicts  : 1048 used of 2048 max
# userid name                uniqueid            connected ping loss state  adr

```

**Comment by BlueHairMinerBoy** [comment]
Latest version, pulled from this repo yesterday.

**Comment by BlueHairMinerBoy** [comment]
Forgot about this issue, sorry. Still getting this issue on the latest version. "FATA[0000] rcon: could not parse timeout duration        err="time: invalid duration \"\"""

**Comment by galexrt** [comment]
@BlueHairMinerBoy Could you please post the output of `srcds_exporter --version` and / or which version are you running?

The error message you posted is not in the code of the `v1.3.2` release..

**Comment by galexrt** [comment]
Closing I wasn't able to reproduce the issue with the v1.3.2 release so far.
